### ISSUE TITLE
good morning guys

### ISSUE THREAD

**Issue by YuHuaOu** [YuHuaOu/FYJ-FrontEnd-FrameWork#4]
good morning guys

**Comment by hzy-499** [comment]
hey bro good morning  too




On 08/06/2020 09:55, 裕华区 wrote:

good morning guys

**Comment by YuHuaOu** [comment]
yo yo ,what's up man! It's a hard work day,i wantna play basketball




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuHuaOu/FYJ-FrontEnd-FrameWork"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午9:58
收件人:&nbsp;"YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;;
抄送:&nbsp;"区"<422841326@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





 hey bro good morning  too
 
 
 
 
 On 08/06/2020 09:55, 裕华区 wrote:
 
 good morning guys

**Comment by hzy-499** [comment]
yep  my bro  it is really hard  , life is  a fucking movie. let us go Lakers




On 08/06/2020 10:00, 裕华区 wrote:

yo yo ,what's up man! It's a hard work day,i wantna play basketball




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YuHuaOu/FYJ-FrontEnd-FrameWork" <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午9:58
收件人:&nbsp;"YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;;
抄送:&nbsp;"区"<422841326@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





hey bro good morning too




On 08/06/2020 09:55, 裕华区 wrote:

good morning guys

**Comment by 600849155** [comment]
i oneders why the project has 3 start?
@hzy-499 @phaseddd

**Comment by hzy-499** [comment]
whomhim is a  ass hole

> i oneders why the project has 3 start?
> @hzy-499 @phaseddd

whomhim is a ass hole

**Comment by phaseddd** [comment]
> i oneders why the project has 3 start?
> @hzy-499 @phaseddd

why cant this project has 3 star?

**Comment by YuHuaOu** [comment]
Lakers champion

**Comment by hzy-499** [comment]
@600849155 @phaseddd @YuHuaOu 
Why can this project have three stars

**Comment by phaseddd** [comment]
> @600849155 @phaseddd @YuHuaOu
> Why can this project have three stars

会不会英语四级过了吗wdnmd

**Comment by phaseddd** [comment]
> Lakers champion
Cavaliers Champion!!

**Comment by hzy-499** [comment]
> > @600849155 @phaseddd @YuHuaOu
> > Why can this project have three stars
> 
> 会不会英语四级过了吗wdnmd

能不能打个标点符号

**Comment by 600849155** [comment]
> > > @600849155 @phaseddd @YuHuaOu
> > > Why can this project have three stars
> > 
> > 
> > 会不会英语四级过了吗wdnmd
> 
> 能不能打个标点符号

我受不了了

**Comment by phaseddd** [comment]
> > > > @600849155 @phaseddd @YuHuaOu
> > > > Why can this project have three stars
> > > 
> > > 
> > > 会不会英语四级过了吗wdnmd
> > 
> > 
> > 能不能打个标点符号
> 
> 我受不了了

不不不不不不不不

**Comment by YuHuaOu** [comment]
湖人总冠军




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "phaseddd"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午4:18
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





     
@600849155 @phaseddd @YuHuaOu
 Why can this project have three stars
  
会不会英语四级过了吗wdnmd
  
能不能打个标点符号
  
我受不了了
  
不不不不不不不不

**Comment by hzy-499** [comment]
> 湖人总冠军
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "phaseddd"<notifications@github.com&gt;; 发送时间: 2020年8月27日(星期四) 下午4:18 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) @600849155 @phaseddd @YuHuaOu Why can this project have three stars 会不会英语四级过了吗wdnmd 能不能打个标点符号 我受不了了 不不不不不不不不 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

nba都没了 还总冠军

**Comment by 600849155** [comment]
> > 湖人总冠军
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "phaseddd"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月27日(星期四) 下午4:18 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<[FYJ-FrontEnd-FrameWork@noreply.github.com](mailto:FYJ-FrontEnd-FrameWork@noreply.github.com)>; 抄送: "区"<[422841326@qq.com](mailto:422841326@qq.com)>; "Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) @600849155 @phaseddd @YuHuaOu Why can this project have three stars 会不会英语四级过了吗wdnmd 能不能打个标点符号 我受不了了 不不不不不不不不 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> nba都没了 还总冠军

傻逼hzy 下班了

**Comment by hzy-499** [comment]
在你下班之前，我就已经下班了
On 08/27/2020 19:03, WhomHim wrote:

湖人总冠军
…
------------------ 原始邮件 ------------------ 发件人: "phaseddd"<notifications@github.com>; 发送时间: 2020年8月27日(星期四) 下午4:18 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com>; 抄送: "区"<422841326@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) @600849155@phaseddd@YuHuaOu Why can this project have three stars 会不会英语四级过了吗wdnmd 能不能打个标点符号 我受不了了 不不不不不不不不 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

nba都没了 还总冠军

傻逼hzy 下班了

**Comment by 600849155** [comment]
good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1

**Comment by YuHuaOu** [comment]
I am open meeting now

**Comment by YuHuaOu** [comment]
Love you guys

**Comment by hzy-499** [comment]
> good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1
@600849155 
good你个头啊good

**Comment by hzy-499** [comment]
> I am open meeting now

fuck you guy

**Comment by 600849155** [comment]
> > good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1
> > @600849155
> > good你个头啊good
不好意思 刚到公司

**Comment by phaseddd** [comment]
> > > good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1
> > > @600849155
> > > good你个头啊good
> 
> 不好意思 刚到公司

有某工作介绍啊whohim

**Comment by YuHuaOu** [comment]
花桥@phaseddd



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "phaseddd"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 上午10:07
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





    
good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1
 @600849155
 good你个头啊good
   
不好意思 刚到公司
  
有某工作介绍啊whohim

**Comment by hzy-499** [comment]
> 花桥@phaseddd
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "phaseddd"<notifications@github.com&gt;; 发送时间: 2020年9月3日(星期四) 上午10:07 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) good morning @phaseddd @YuHuaOu @hzy-499 @youqingcheng1 @600849155 good你个头啊good 不好意思 刚到公司 有某工作介绍啊whohim — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么取消别人issue，我不收到邮件

**Comment by 600849155** [comment]
能不能群聊？

**Comment by hzy-499** [comment]
怎么取消别人issue，我不收到邮件

**Comment by 600849155** [comment]
> 怎么取消别人issue，我不收到邮件

点右上角 unwatch 不就行了吗

**Comment by phaseddd** [comment]
good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了

**Comment by 600849155** [comment]
> good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了

不修 滚Σ(☉▽☉"a

**Comment by hzy-499** [comment]
> > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> 
> 不修 滚Σ(☉▽☉"a

guys表示复数 不用加们

**Comment by hzy-499** [comment]
> > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> 
> 不修 滚Σ(☉▽☉"a

雨好大啊 whohim

**Comment by YuHuaOu** [comment]
> good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了

阁下是bug王？

**Comment by YuHuaOu** [comment]
> > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > 
> > 
> > 不修 滚Σ(☉▽☉"a
> 
> 雨好大啊 whohim

早餐吃什么

**Comment by hzy-499** [comment]
> > > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > > 
> > > 
> > > 不修 滚Σ(☉▽☉"a
> > 
> > 
> > 雨好大啊 whohim
> 
> 早餐吃什么

每天都是营养快线

**Comment by YuHuaOu** [comment]
> > > > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > > > 
> > > > 
> > > > 不修 滚Σ(☉▽☉"a
> > > 
> > > 
> > > 雨好大啊 whohim
> > 
> > 
> > 早餐吃什么
> 
> 每天都是营养快线

整点猪脚饭吗

**Comment by hzy-499** [comment]
> > > > > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > > > > 
> > > > > 
> > > > > 不修 滚Σ(☉▽☉"a
> > > > 
> > > > 
> > > > 雨好大啊 whohim
> > > 
> > > 
> > > 早餐吃什么
> > 
> > 
> > 每天都是营养快线
> 
> 整点猪脚饭吗

有毛病

**Comment by 600849155** [comment]
> > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > 
> > 
> > 不修 滚Σ(☉▽☉"a
> 
> 雨好大啊 whohim

大塘没下雨啊

**Comment by hzy-499** [comment]
> > > > good morning啊guys们 @YuHuaOu @hzy-499 @600849155 @youqingcheng1 新的修bug的一周开始了
> > > 
> > > 
> > > 不修 滚Σ(☉▽☉"a
> > 
> > 
> > 雨好大啊 whohim
> 
> 大塘没下雨啊

let s go  lakers

**Comment by hzy-499** [comment]
what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1

**Comment by 600849155** [comment]
> what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1

i am doing something interesting project

**Comment by hzy-499** [comment]
> > what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1
> 
> i am doing something interesting project

something interestion bug

**Comment by hzy-499** [comment]
> > what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1
> 
> i am doing something interesting project

something unteresting bug

**Comment by phaseddd** [comment]
> > what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1
> 
> i am doing something interesting project

IM thouching the fish and get ready to going off work now

**Comment by 600849155** [comment]
> > > what are you doing now gays @600849155 @phaseddd @YuHuaOu @youqingcheng1
> > 
> > 
> > i am doing something interesting project
> 
> IM thouching the fish and get ready to going off work now

羡慕 还有饭堂

**Comment by 600849155** [comment]
@phaseddd @YuHuaOu @hzy-499 @youqingcheng1  Rain is so heavy today

**Comment by hzy-499** [comment]
> @phaseddd @YuHuaOu @hzy-499 @youqingcheng1 Rain is so heavy today

yep it is so big

**Comment by YuHuaOu** [comment]
funny mud pee

**Comment by 600849155** [comment]
good morning guys~

**Comment by phaseddd** [comment]
> good morning guys~

fuck you man~

**Comment by hzy-499** [comment]
why no code

**Comment by 600849155** [comment]
> why no code

what does your mean？

**Comment by phaseddd** [comment]
火箭输了艹

**Comment by YuHuaOu** [comment]
你一骑士球迷不要过来捣乱

**Comment by phaseddd** [comment]
> 你一骑士球迷不要过来捣乱

wdnmd我是勇士球迷

**Comment by phaseddd** [comment]
> 你一骑士球迷不要过来捣乱

谁垫底我粉谁，我就是输球密

**Comment by hzy-499** [comment]
I will be the No.1 of the front-end engineer

**Comment by hzy-499** [comment]
good morning boys and girls

**Comment by phaseddd** [comment]
> good morning boys and girls

火箭输了艹

**Comment by hzy-499** [comment]
lets go heat

**Comment by YuHuaOu** [comment]
let's go juejin




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 上午9:38
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





 
lets go heat

**Comment by phaseddd** [comment]
> let's go juejin
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年9月16日(星期三) 上午9:38 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) lets go heat — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

掘金输了艹

**Comment by hzy-499** [comment]
i am the Lakers fan ,who are you

**Comment by YuHuaOu** [comment]
go qishi go!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年9月21日(星期一) 下午2:54
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





  
let's go juejin
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年9月16日(星期三) 上午9:38 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) lets go heat — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
掘金输了艹

**Comment by hzy-499** [comment]
laji yuhuaou

**Comment by YuHuaOu** [comment]
nihaoxiaozhang




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年9月21日(星期一) 下午3:14
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





 
laji yuhuaou

**Comment by phaseddd** [comment]
fuck hzy

**Comment by hzy-499** [comment]
fuck Mr.Lin

**Comment by YuHuaOu** [comment]
Nighty night ! Boys!



---Original---

**Comment by YuHuaOu** [comment]
live ia a fxxking movie



---Original---

**Comment by hzy-499** [comment]
hi  everybody  i am very happy  becsuse i do not ot tonight

**Comment by YuHuaOu** [comment]
Amazing! Congratulation! Wish you happy every times!



---Original---

**Comment by hzy-499** [comment]
湖人总冠军

**Comment by YuHuaOu** [comment]
long time no see! gays!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:36
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





 
湖人总冠军

**Comment by hzy-499** [comment]
> long time no see! gays!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:36 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) 湖人总冠军 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

hello Michael

**Comment by YuHuaOu** [comment]
Are you busy&nbsp;recently？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:39
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





  
long time no see! gays!
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:36 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) 湖人总冠军 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
hello Michael

**Comment by hzy-499** [comment]
sometimes  my friend

**Comment by hzy-499** [comment]
> Are you busy&nbsp;recently？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:39 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) long time no see! gays! … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:36 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) 湖人总冠军 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. hello Michael — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hzy-499** [comment]
> Are you busy&nbsp;recently？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:39 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) long time no see! gays! … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:36 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) 湖人总冠军 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. hello Michael — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

<p>why&nbsp;</p>

**Comment by hzy-499** [comment]
> > Are you busy recently？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年10月22日(星期四) 下午3:39 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<[FYJ-FrontEnd-FrameWork@noreply.github.com](mailto:FYJ-FrontEnd-FrameWork@noreply.github.com)>; 抄送: "区"<[422841326@qq.com](mailto:422841326@qq.com)>; "Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) long time no see! gays! … ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年10月22日(星期四) 下午3:36 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<[FYJ-FrontEnd-FrameWork@noreply.github.com](mailto:FYJ-FrontEnd-FrameWork@noreply.github.com)>; 抄送: "区"<[422841326@qq.com](mailto:422841326@qq.com)>; "Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) 湖人总冠军 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. hello Michael — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> why

<p style="font-color: blue;">test</p>

**Comment by YuHuaOu** [comment]
oh,that is nice ,will you come ShenZhen this weekend? let's drink something




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午3:57
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





 
sometimes  my friend

**Comment by hzy-499** [comment]
> oh,that is nice ,will you come ShenZhen this weekend? let's drink something
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:57 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) sometimes my friend — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

sorry man this weekend i have something to do

**Comment by YuHuaOu** [comment]
oh , fxxk you man




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午4:01
收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 
抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4)





  
oh,that is nice ,will you come ShenZhen this weekend? let's drink something
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2020年10月22日(星期四) 下午3:57 收件人: "YuHuaOu/FYJ-FrontEnd-FrameWork"<FYJ-FrontEnd-FrameWork@noreply.github.com&gt;; 抄送: "区"<422841326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [YuHuaOu/FYJ-FrontEnd-FrameWork] good morning guys (#4) sometimes my friend — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
sorry man this weekend i have something to do

**Comment by hzy-499** [comment]
no fk word
